Vagrant.configure(2) do |config|
    # образ системы centos/7
    config.vm.box = "centos/7"
    # не проверять репозиторий на наличие обновлений
    config.vm.box_check_update = false
  
    # ПЕРВАЯ ВИРТУАЛЬНАЯ МАШИНА
    config.vm.define "vm1" do |subconfig|
      # имя виртуальной машины
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "vm1"
      end
      # hostname виртуальной машины
      subconfig.vm.hostname = "vm1"
      # настройки сети
      subconfig.vm.network "public_network", ip: "192.168.0.117", bridge: "Intel(R) Wireless-AC 9462"
      # установка пакетов
      subconfig.vm.provision "tools", type: "shell", inline: "sudo yum -y install vim htop mc tree net-tools"
    end
  
    # ВТОРАЯ ВИРТУАЛЬНАЯ МАШИНА
    config.vm.define "vm2" do |subconfig|
      # имя виртуальной машины
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "vm2"
      end
      # hostname виртуальной машины
      subconfig.vm.hostname = "vm2"
      # настройки сети
      subconfig.vm.network "public_network", ip: "192.168.0.118", bridge: "Intel(R) Wireless-AC 9462"
      # установка пакетов
      subconfig.vm.provision "tools", type: "shell", inline: "sudo yum -y install vim htop mc tree net-tools"
    end
    
    # обновление системы (для первой и второй)
    config.vm.provision "update", type: "shell", inline: "sudo yum -y update"
end